services:
  api:
    build: .
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ADMIN_KEY: ${ADMIN_KEY}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ConnectionStrings__Default: "Server=sql-server,1433;Database=${DATABASE_NAME};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True"
      ConnectionStrings__Redis: "redis:6379"
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      sql-server:
        condition: service_healthy

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lin-dev
    hostname: lin-dev
    networks:
      - ubuntu_net
    ports:
      - "2222:22"
    volumes:
      - ./src/FeatureFlags.Api:/home/dev/FeatureFlags.Api
    restart: unless-stopped

networks:
  ubuntu_net:
    driver: bridge