# docker-compose.yaml
services:
  redis:
    image: redis:7.0-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  sql-server:
    build:
      context: .
      dockerfile: Dockerfile.sql-server
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  redisdata:
  sqlserverdata:
